### ISSUE TITLE
Multimodal-video-emotion-recognition-pytorch

### ISSUE THREAD

**Issue by Mi12Mi12Cu** [vishaal27/Multimodal-Video-Emotion-Recognition-Pytorch#2]
Hi good day, Am currently working on data fusion and stumbled upon your code. It has been of great help but it seems the code isn't finished yet. Am really intrested in this and would like to know if you were able to finish working on the code especially in applying the emotions after fusing the audio, video and text dataset together. Thanks, awaiting your response

**Comment by vishaal27** [comment]
Hi,
The code is completed and all the experimental results and analyses are presented in the Report.pdf file in the github repository. I am not sure if you are asking for any other emotion classification experiments, but I have run my experiments only on the RAVDESS dataset (which can be found here: https://zenodo.org/record/1188976#.YV1qp55ue3I). I **do not** use text as a modality and am fusing only the visual and audio modalities. More information on this can be found in the report attache with the repository.

**Comment by Mi12Mi12Cu** [comment]
Thank you for your response. Am very grateful

**Comment by Mi12Mi12Cu** [comment]
Thanks, truly helpful.

**Comment by Mi12Mi12Cu** [comment]
Hi, am still not so clear, i have successfully ran the code and it works just fine, what I would like to know is how to predict the emotions. Angry, sad, happy, neutral. And also if it can be implemented in real time. Thanks, awaiting response
